version: '3.7'

services:
  website-change-checker:
    image: website-change-checker:latest
    build: .
    restart: never
    secrets:
      - website-change-checker-config.json

secrets:
  website-change-checker-config.json:
    external: true