version: '3.7'

services:
  website-change-checker:
    image: website-change-checker:latest
    environment:
      - PYTHONUNBUFFERED=1
    volumes: 
        - './configs:/configs'
    build: .
    restart: always
