version: '3.7'

services:
  website-change-checker:
    image: website-change-checker:latest
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    secrets:
      - website-change-checker-config.json

secrets:
  website-change-checker-config.json:
    external: true